using AutoMapper;
using CarAccessoriesShop.Application.DTOs.Invertory.QueryDtos;
using CarAccessoriesShop.Application.Features.Inventories.Requests.Commands;
using CarAccessoriesShop.Application.Presistences.UnitofWork;
using MediatR;

namespace CarAccessoriesShop.Application.Features.Inventories.Handlers.Commands;

internal class InsertInventoryRequestHandler(IUnitofWork unitofWork, IMapper mapper) : IRequestHandler<InsertInventoryRequest, InventoryDto>
{
    public async Task<InventoryDto> Handle(InsertInventoryRequest request, CancellationToken cancellationToken)
    {
        // map InsertInvetoryDto to Inventory entity
        var inventory = mapper.Map<Domain.Entity.Main.Inventory>(request.Invetory);
        // ID will be generated by the database
        await unitofWork.InventoryRepo.AddAsync(inventory);
        await unitofWork.SaveChangesAsync(cancellationToken);
        // after saving changes, the inventory object will have its ID populated
        return mapper.Map<InventoryDto>(inventory);
    }
}

